import time
def visualize(j, Q, S, bs):
  print("Current score is: ", bs)     
  print(S[j:j+len(Q)])
  for i in range(len(S[j:j+len(Q)])):
    if Q[i] == S[j:j+len(Q)][i]:
      print("|", end="")
    else:
      print("X", end="")
  print()
  print(Q)

S = "TATGGACCGGGTCATCAATAGGTTATAGCCTTGTAGTTAACATGTAGCCCGGCCCTATTAGTACAGTAGTGCCTTCATCGGCATTCTGTTTATTAAGTTTTTTCTACAGCAAAACGATCAAGTGCACTTCCACAGAGCGCGGTAGAGACTCATCCACCCGGCAGCTCTGTAATAGGGACTAAAAAAGTGATGATAATCATGAGTGCCGCGTTATGGTGGTGTCGGATCAGAGCGGTCTTACGACCAGTCGTATGCCTTCTCGAGTTCCGTCCGGTTAAGCGTGACAGTCCCAGTGAACCCACAAACCGTGATGGCTGTCCTTGGAGTCATACGCAAGAAGGATGGTCTCCAGACACCGGCGCACCAGTTTTCACGCCGAAAGCATAAACGACGAGCACATATGAGAGTGTTAGAACTGGACGTGCGGTTTCTCTGCGAAGAACACCTCGAGCTGTTGCGTTGTTGCGCTGCCTAGATGCAGTGTCGCACATATCACTTTTGCTTCAACGACTGCCGCTTTCGCTGTATCCCTAGACAGTCAACAGTAAGCGCTTTTTGTAGGCAGGGGCTCCCCCTGTGACTAACTGCGCCAAAACATCTTCGGATCCCCTTGTCCAATCTAACTCACCGAATTCTTACATTTTAGACCCTAATATCACATCATTAGAGATTAATTGCCACTGCCAAAATTCTGTCCACAAGCGTTTTAGTTCGCCCCAGTAAAGTTGTCTATAACGACTACCAAATCCGCATGTTACGGGACTTCTTATTAATTCTTTTTTCGTGAGGAGCAGCGGATCTTAATGGATGGCCGCAGGTGGTATGGAAGCTAATAGCGCGGGTGAGAGGGTAATCAGCCGTGTCCACCAACACAACGCTATCGGGCGATTCTATAAGATTCCGCATTGCGTCTACTTATAAGATGTCTCAACGGTATCCGCAACTTGCGATGTGCCTGCTATCCTTAAATGCATATCTCGCCCAGTAGCTTCCCAATATG"
Q = "CTAAGGGTTTCAGCACGGGTCGAGCCGTTCGTCTGCGAAGAA"

best_score_index = 0
best_score = 0

for j in range(len(S)-len(Q)):
    cum_score = 0
    min_score = 0
    for i in range(len(Q)):

      if Q[i] == S[j+i]:
        cum_score += 1
      else:
        cum_score -= 1

      if cum_score < min_score:
        min_score = cum_score
      
      if (cum_score - min_score) > best_score:
        best_score = cum_score - min_score 
        best_score_index = j

print(S[best_score_index:best_score_index+len(Q)])
for i in range(len(Q)):
  if Q[i] == S[best_score_index+i]:
    print("|", end="")
  else:
    print("X", end="")
print()
print(Q)


